# Envs

# XDG Configs
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.local/cache"

# Editor
export EDITOR="nvim"

export DOTFILES="$HOME/.dotfiles"
# zsh config
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"

# golang
export GOPATH="$HOME/go"
export PATH="$GOPATH/bin:$PATH"

# npm
export NPM_CONFIG_PREFIX="$XDG_CONFIG_HOME/npm/"
export PATH="${NPM_CONFIG_PREFIX}bin:$PATH"
