# zshrc config

# aliases
source $HOME/.dotfiles/aliases

# autocompletion
if type brew &>/dev/null; then
   FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"
fi
autoload -Uz compinit; compinit
autoload -Uz ${ZDOTDIR}/extra/prompt; prompt
