# zshrc config

# aliases
source $HOME/.dotfiles/aliases

# autocompletion
if type brew &>/dev/null; then
   FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"
fi
autoload -Uz compinit; compinit
autoload -Uz ${ZDOTDIR}/extra/prompt; prompt

setopt HIST_SAVE_NO_DUPS

# rust
if [ -f $HOME/.cargo/env ]; then
    . "$HOME/.cargo/env"
fi

# machine specific
if [ -f $HOME/.grgrc  ]; then
   source $HOME/.grgrc
fi
